### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by jpschewe** [exsilium/mungit#8]
I'm rather new to node, so I probably am doing something wrong, but I'm running into a problem installing from the git repository.

I cloned the repository and I'm trying to install from the working directory.
```
npm ERR! Linux 4.13.0-17-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "."
npm ERR! node v6.11.4
npm ERR! npm  v3.5.2
npm ERR! path /home/jpschewe/npm-global/lib/node_modules/.staging/abbrev-5cbd07e4
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/home/jpschewe/npm-global/lib/node_modules/.staging/abbrev-5cbd07e4' -> '/home/jpschewe/npm-global/lib/node_modules/mungit/node_modules/npm/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/home/jpschewe/npm-global/lib/node_modules/.staging/abbrev-5cbd07e4' -> '/home/jpschewe/npm-global/lib/node_modules/mungit/node_modules/npm/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jpschewe/src/mungit/npm-debug.log
npm ERR! code 1
```
[npm-debug.log](https://github.com/exsilium/mungit/files/1530849/npm-debug.log)

**Comment by jpschewe** [comment]
Doing `npm uninstall -g mungit` and then doing the install again gets me passed this install error. However when I try and run again I get:
```
>ungit
module.js:471
    throw err;
    ^

Error: Cannot find module '../src/config'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jpschewe/npm-global/lib/node_modules/mungit/bin/ungit:3:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

~/src/mungit
```

Versions:
```
 >node --version
v6.11.4
```

SHA-1: f5ec070e

**Comment by exsilium** [comment]
Hi! When installing from the git repo, please see the `CONTRIBUTING.md` file for installation instructions. Make sure that you have the `grunt-cli` package globally installed and after `npm install` also run the build script: `npm run build`. I hope this helps. Cheers! 🍻

**Comment by jpschewe** [comment]
That works great. I can run from the git repo just fine. Thank you!
